#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_python {
  if type "pip" > /dev/null; then
    einf "Python already installed... skipping"
    return
  fi

  einf "Installing python"
  brew install python
  brew install python3
  brew install autoenv

  einf "Upgrading pip"
  pip install --upgrade pip
  pip install --upgrade setuptools

  einf "Installing virtualenv"
  pip install virtualenv
  pip install virtualenvwrapper

  rm virtualenvs
  mkdir virtualenvs
  ln -sF $DOTFILES/virtualenvs ~/.virtualenvs

  source /usr/local/bin/virtualenvwrapper.sh

  mkvirtualenv --python=`which python3` venv
  workon venv

  export PIP_REQUIRE_VIRTUALENV=true
  export PIP_DOWNLOAD_CACHE=$HOME/Library/Caches/pip

  einf "Installing packages"
  pip install awsebcli
  pip install powerline-status
  pip install pyodbc
}

askdo install_python "Install python?"