#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_python {
  if type "pip" > /dev/null; then
    einf "Python already installed... skipping"
    return
  fi

  einf "Installing python"
  brew install python
  brew install python3
  brew install autoenv

  einf "Upgrading pip"
  pip3 install --upgrade pip
  pip3 install --upgrade setuptools

  einf "Installing virtualenv"
  pip3 install virtualenv
  pip3 install virtualenvwrapper

  rm -rf ~/.virtualenvs
  rm -rf virtualenvs
  mkdir virtualenvs
  ln -sF $DOTFILES/virtualenvs ~/.virtualenvs

  export VIRTUALENVWRAPPER_PYTHON=`which python3`
  source /usr/local/bin/virtualenvwrapper.sh

  mkvirtualenv --python=`which python3` venv
  workon venv

  export PIP_REQUIRE_VIRTUALENV=true
  export PIP_DOWNLOAD_CACHE=$HOME/Library/Caches/pip3

  einf "Installing packages"
  pip3 install awsebcli
  pip3 install powerline-status
  pip3 install pyodbc
}

askdo install_python "Install python?"