#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install vscode extensions
function install_packages {
  if ! type "code" > /dev/null; then
    eerr "VSCode must be installed first..."; exit 1
  fi

  einf "Installing VSCode packages"
  cat $CODE_PACKAGES | xargs code --install-extension
}

askdo install_packages "Install VSCode extensions?"