#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function install_managers {
  if [ ! type "n"  > /dev/null 2>&1 ]; then
    einf "Installing n"
    curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y
  else
    printf "n already installed... skipping\n"
  fi

  if [ ! type "chruby"  > /dev/null 2>&1 ]; then
    einf "Installing chruby"
    brew install chruby --HEAD
    brew install ruby-install --HEAD
  else
    printf "chruby already installed... skipping\n"
  fi

  if [ ! type "antigen"  > /dev/null 2>&1 ]; then
    einf "Installing antigen"
    git clone https://github.com/zsh-users/antigen $VENDOR/zsh-antigen
  else
    printf "antigen already installed... skipping\n"
  fi

  if [ ! type "vundle"  > /dev/null 2>&1 ]; then
    einf "Installing vundle"
    git clone https://github.com/VundleVim/Vundle.vim.git $VENDOR/zsh-antigen
  else
    printf "antigen already installed... skipping\n"
  fi

  if [ type "npm" && ! type "yarn" > /dev/null 2>&1 ]; then
    einf "Installing yarn"
    npm i yarn -g
  else
    printf "yarn already installed... skipping\n"
  fi
}

askdo install_managers "Install managers (n / chruby / antigen / yarn)?"