#!/bin/sh

# import helpers
source `dirname $0`/helpers

# Install brew
function setup_env {
  einf "Linking shell configs"
  ln -sF $DOTFILES_SHELL/functions ~/.functions.sh
  ln -sF $DOTFILES_SHELL/exports ~/.exports.sh
  ln -sF $DOTFILES_SHELL/aliases ~/.aliases.sh
  ln -sF $DOTFILES_SHELL/antigen ~/.antigen.sh
  ln -sF $DOTFILES_SHELL/profile ~/.profile
  ln -sF $DOTFILES_SHELL/zshrc ~/.zshrc
  ln -sF $DOTFILES_SHELL/hyper.js ~/.hyper.js

  einf "Linking editor configs"
  ln -sF $DOTFILES_EDITORS/.vim ~/
  ln -sF $DOTFILES_EDITORS/vimrc ~/.vimrc

  # VSCode Configuration File, attempt to remove existing settings and link ours
  mv $HOME/Library/Application\ Support/Code/User/settings.json $HOME/Library/Application\ Support/Code/User/settings.json.bak
  ln -sF $DOTFILES_EDITORS/vscode.json $HOME/Library/Application\ Support/Code/User/settings.json

  einf "Linking github configs"
  ln -sF $DOTFILES_SHELL/gitconfig ~/.gitconfig
  ln -sF $DOTFILES_SHELL/gitignore ~/.gitignore
}

askdo setup_env "Setup environment?"
